name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.18', '1.19']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Build app
        run: |-
          go build -ldflags="-w -s" .
